# action.yml

name: 'Customizable Project Heatmap'
description: 'Generates a heatmap of project hotspots based on activity, contributors, and complexity.'
inputs:
  threshold:
    description: 'Activity threshold for hotspots'
    required: false
    default: '10'
  time_range:
    description: 'Time range for analysis (in days)'
    required: false
    default: '30'
outputs:
  heatmap_url:
    description: 'Path to the generated heatmap image'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
branding:
  icon: 'shield'
  color: 'green'